### ISSUE TITLE
read-package-json is a prerequisite for adding the plugin

### ISSUE THREAD

**Issue by lasselaakkonen** [dpa99c/cordova-custom-config#10]
Adding this plugin runs https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/resolveDependencies.js which tries to install read-package-json, but resolveDependencies.js itself is dependent on read-package-json.

**Comment by dpa99c** [comment]
True, but since read-package-json is a [dependency of npm](https://github.com/npm/npm/blob/master/package.json#L81), if it's not installed, then either npm isn't installed or it's not installed correctly. But you're right, the plugin doesn't need to try to install a dependency which should already be there.

**Comment by lasselaakkonen** [comment]
Hmm, yep. Didn't realize it was a dependency of npm. My setup must be somehow wonky, had to install read-package-json separately.
