### ISSUE TITLE
Error updating config for platform 'ios

### ISSUE THREAD

**Issue by shi11** [dpa99c/cordova-custom-config#100]
Hi, just tried your plugin for the first time. It could be something funky on my end, though I'm not sure what but I'm getting this when I try to build
```
 Error updating config for platform 'ios': ENOENT: no such file or directory, open '/Users/username/Javascript/project/platforms/ios/projectname
    /projectname
    -Info.plist'
```
I think for some reason it's putting in those line breaks after my projectname thus making it seem like the -Info.plist file doesn't exist?

**Comment by dpa99c** [comment]
It seems this error is being raised due to a new line character being injected into the `projectName` variable. This results in the error when it used to [generate the path to the plist file](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/applyCustomConfig.js#L792). `projectName` is derived by [reading the `<name>` element from the project `config.xml`](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/fileUtils.js#L64). 

So check your `config.xml` to make sure a linebreak doesn't exist inside of the `<name>` element.

You can also try building and running the [example project](https://github.com/dpa99c/cordova-custom-config-example) to validate the plugin in your build environment.

**Comment by shi11** [comment]
yup that was it. thanks!
