### ISSUE TITLE
[iOS] Plugin breaks {APPNAME}.entitlements set by other plugins

### ISSUE THREAD

**Issue by chancezeus** [dpa99c/cordova-custom-config#101]
I have a project depending on (a lot of) other plugins and I'm using this plugin to add some permissions/features to Android (for use with WebRTC through crosswalk) and an additional framework (AdSupport.framework) to iOS (for use with "chemerisuk/cordova-plugin-firebase-analytics").

The problem is (and I could not find why/how from the sources) one of the other plugins (nordnet/cordova-universal-links-plugin), creates an additional entitlements file and adds it to the project file (or at least is supposed to), but when compiling this file is no longer included. In the issues of this plugin (nordnet/cordova-universal-links-plugin#8) it is mentioned that the culprit is this plugin, so I was wondering how and if this is true why this happens. If it is related to this plugin, maybe a fix is in order since multiple plugins use dynamic creation/addition of entitlements (the cordova branch.io plugin for example) and all of them will be affected if this plugin is breaking the "{APPNAME}.entitlements" inclusion into the projects build file

For now I have temporarely fixed it by adding the required associated domains manually (through this plugin actually), but please look into it and (if possible) get back with a proper fix/solution...

**Comment by djett41** [comment]
BTW the following plugins also seem to modify the path to the entitlements file and create the file in Resources

branch-cordova-sdk
cordova-plugin-googleplus

**Comment by dpa99c** [comment]
I'm unable to reproduce a scenario where this plugin causes the loss of the reference to the entitlements file created by the universal links plugin - see [this screencapture](http://ge.tt/4P4C2Mj2) for my test results.

As can be seen from the [source code](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/applyCustomConfig.js), this plugin makes no explicit references to the `CODE_SIGN_ENTITLEMENTS` key in the XCBuildConfiguration sections of the `project.pbxproj`, so it should only operate on it if an explicit custom config `<preference>` or `<config-file>` block is added to the project `config.xml`.

It's possible a race condition could be present since both plugins use `after_prepare` hooks to make modifications to the `project.pbxproj` file, hence the issue could be intermittent. If the hook scripts for the two plugins are running concurrently, one could theorise that it would be possible for the changes made to the pbxproj file by one plugin to be overwritten by the other.

This plugin [returns a promise](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/applyCustomConfig.js#L942) which prevents the Cordova build process from progressing until the plugin script is finished and the promise has been resolved, however the universal links plugin [does not](https://github.com/nordnet/cordova-universal-links-plugin/blob/master/hooks/afterPrepareHook.js#L18) return a promise, hence its operations could in theory still be underway when Cordova initiates this plugin's `after_prepare` script.

If anyone is able to reliably reproduce this issue, please post the steps to reproduce the issue, and I will investigate further.

**Comment by dpa99c** [comment]
Closing due to no response by OP

**Comment by dpa99c** [comment]
Update: I found and [fixed a bug](https://github.com/dpa99c/cordova-custom-config/commit/74b43fe6dd4e93abc90d0a025bc5976088d4fbc4) (see [#108](https://github.com/dpa99c/cordova-custom-config/issues/108)) which should also resolve this issue. 

This has been published in a patch release: `cordova-custom-config@3.1.3`

**Comment by MarsupiL** [comment]
I'm running into this issue again with the phonegap-plugin-push 2.0.0-rc3 (see https://github.com/nordnet/cordova-universal-links-plugin/issues/8)
Setting the following config adds the key to the Entitlements-Release.plist but prevents cordova (ios 4.4.0) from adding it to the <project>.entitlements file.
```
<config-file platform="ios" target="Entitlements-Release.plist" parent="aps-environment" mode="replace">
<string>production</string>
</config-file>
```

**Comment by JimDrury** [comment]
Seeing same issue as @MarsupiL

**Comment by dpa99c** [comment]
@MarsupiL The above `<config-file>` block will just cause this plugin to modify the target plist file (as intended). So how does that relate to what the Cordova CLI adds to the `.entitlements` file?

**Comment by MarsupiL** [comment]
@dpa99c The modification of the target .plist file does work indeed. The issue seems to come from the XCode IDE 
https://issues.apache.org/jira/browse/CB-11854?focusedCommentId=15770323&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15770323
So the plugin might have to readjust to a .entitlements extension instead of .plist for the next cordova-ios release.
