### ISSUE TITLE
dict key/value pairs are sorted before being inserted

### ISSUE THREAD

**Issue by b12f** [dpa99c/cordova-custom-config#106]
I've been trying to get the Branch cordova SDK working, and had the following config-file tag:

```
<config-file mode="replace" parent="branch_key" target="*-Info.plist">
  <dict>
    <key>test</key>
    <string>key_test_censored</string>
    <key>live</key>
    <string>key_live_censored</string>
  </dict>
</config-file>
```
The problem is that these get rearranged to the following:

```
<config-file mode="replace" parent="branch_key" target="*-Info.plist">
  <dict>
    <key>test</key>
    <key>live</key>
    <string>key_test_censored</string>
    <string>key_live_censored</string>
  </dict>
</config-file>
```
This obviously breaks the generated plist file.

I've been going through your code but I cannot really determine whether this is a problem on your part of the XML parser. In any case, this broke my build and I had to resort to the following:
```
<config-file mode="merge" parent="branch_key" target="*-Info.plist">
  <dict>
    <key>test</key>
    <string>key_test_censored</string>
  </dict>
</config-file>
<config-file mode="merge" parent="branch_key" target="*-Info.plist">
  <dict>
    <key>live</key>
    <string>key_live_censored</string>
  </dict>
</config-file>
```

Which is less than optimal, since now only the live key gets written, even though mode="merge"

**Comment by dpa99c** [comment]
I'm unable to reproduce the issue you describe (which is unsurprising since the plugin doesn't perform any kind of sorting on the content elements of injected <config-file> blocks). See [this screencapture](http://ge.tt/1YP11Mj2) which illustrates the results I get in an isolated test case.

Is it possible another plugin or library is manipulating your plist so as to cause sorting of the injected keys?

**Comment by dpa99c** [comment]
Closing due to no response by OP

**Comment by geshub** [comment]
Hi,
I see the exact same reordering problem.
I've seen your video so it's probably not linked to the plugin.
Anyone else found what's causing the problem ?

**Comment by dpa99c** [comment]
@geshub It might be a conflict with another plugin or another plugin itself causing the issue.
Can you list the plugins used in the project in which you're encountering the issue?

It would also be great if you could run `cordova prepare --verbose` and post the log output.

**Comment by geshub** [comment]
@dpa99c 
It was a conflict with another hook reading the config.xml, sorry for that !
Thanks for your help.

**Comment by ChrisEelmaa** [comment]
I had the same problem. After some investigation I've come to a conclusion.

The architecture of "config-file" plugin should be modified a little bit because every time some plugin tries to automagically auto-format code, it breaks completely.

Not only that, but developers keep checking in the "malformed" config.xml. 

In fact, this happens with some of the plugins, but it also happens when you run "ionic resources" (which is part of my CI), and every time someone updates splash screen / icons, they have to be very careful not to check in the incorrect config.xml.

"ionic resources" is using xml2js and the default option is preserveChildrenOrder: false, which I can't override anyhow.

I propose this solution:

Add an extra option to config-file tag, which lets you read the fragment out of external file, as such:

```
 <config-file parent="CFBundleDocumentTypes" target="MyApp-Info.plist"  fragment="untouched.xml" />
```

where untouched.xml is

```
<array>
  <dict>
    <key>CFBundleTypeName</key>
    <string>Epub Files</string>
    <key>LSItemContentTypes</key>
    <array>
      <string>org.idpf.epub-container</string>
    </array>
    <key>LSHandlerRank</key>
    <string>Owner</string>
  </dict>
</array>
```
