### ISSUE TITLE
Cannot install plugin "Failed to fetch plugin"

### ISSUE THREAD

**Issue by tobiasmuecksch** [dpa99c/cordova-custom-config#133]
I've started a brand new Cordova project and tried to add this plugin, but ran into the following error

The command I've entered:
```
> cordova plugin add cordova-custom-config --save
```

**The error:**
```
Error: Failed to fetch plugin git+https://github.com/dpa99c/cordova-custom-config.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

[ERROR] An error occurred while running cordova plugin add cordova-custom-config --save (exit code 1).
```

Installing other plugins works without any problems. Is it just me or is this a known error?

**Comment by dpa99c** [comment]
Something is screwy there because you've referenced the plugin by its ID on npm, [cordova-custom-config](https://www.npmjs.com/package/cordova-custom-config), yet the URL it corresponds to is the github URL.

I would do the following:
- Remove the plugin (if it exists at all) : `cordova plugin rm cordova-custom-config`
- Remove it from `node_modules/` (if it exists): `rm -Rf node_modules/cordova-custom-config`
- Remove any entry for it from `plugins/fetch.json`
- Try adding it again

If that fails, try adding direct from the Github repo:

    cordova plugin add https://github.com/dpa99c/cordova-custom-config.git

Also make sure you're using `cordova@7` CLI.

**Comment by tobiasmuecksch** [comment]
Thank you for the fast reply, you've pointed me in the right direction.

In my case, one of my plugins had a broken dependency reference to this plugin which somehow interfered...
