### ISSUE TITLE
i am getting this error when i build or serve the ionic app

### ISSUE THREAD

**Issue by shatrudhan** [dpa99c/cordova-custom-config#134]
Error: Cannot find module 'elementtree'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\s-ionic\ribblu-ionic-1.0.2\node_modules\ionic\node
_modules\@ionic\cli-utils\lib\cordova\config.js:6:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by dpa99c** [comment]
At a first glance, that error does not appear to arise from this plugin:

While this plugin [depends on](https://github.com/dpa99c/cordova-custom-config/blob/master/package.json#L33) and [uses](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/applyCustomConfig.js#L1004) `elementtree`, the stacktrace you have posted doesn't correspond to the hook scripts of this plugin. This is because the [loading of dependencies](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/applyCustomConfig.js#L1001) is explicitly wrapped in a [try/catch block](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/applyCustomConfig.js#L1062) to handle dependency errors. Therefore I'd expect the error, if caused by this plugin's hook scripts, to look more like that in #120, i.e.

    Error: Error loading dependencies - ensure the plugin has been installed via cordova-fetch or run 'npm install cordova-custom-config': Cannot find module 'elementtree'

If you think this plugin is the cause of your error, please give additional information:

- version of:
  - cordova CLI
  - npm
  - node
  - this plugin
- exact CLI command causing the error
- full verbose output of the above command (run with `--verbose`)

Also see the [installation](https://github.com/dpa99c/cordova-custom-config#installation) section in the documentation.

**Comment by dpa99c** [comment]
Closed due to no response from OP
