### ISSUE TITLE
Missing dependency error

### ISSUE THREAD

**Issue by alain-sarti** [dpa99c/cordova-custom-config#144]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

We have a MacBook as a dedicated build machine and the local developer MacBooks. On my local MacBook the plugin works as intended, which is awesome.
But after that I push the changes to the git repository, our MacBook checks the branch out into an empty directory and runs npm install, followed by adding the ios platform and building it. So it's just another local machine in that regard.
But the build machine cannot build an ios app.

The error is:
```
Error: cordova-custom-config: Error loading dependencies for applyCustomConfig.js - ensure the plugin has been installed via cordova-fetch or run 'npm install cordova-custom-config': Cannot find module 'simple-plist'
```

Even if I ssh onto that MacBook and install the plugin, it does not run. The node_modules folder does contain the simple-plist module.

**Expected behavior:**

It should run just like on my local machine :)

**Environment information**

- Cordova CLI version 
	- 7.1.0
- Cordova platform version
	- ios 4.5.4
- Plugins & versions installed in project (including this plugin)
    - com-sarriaroman-photoviewer 1.1.16 "PhotoViewer"
    - cordova-custom-config 5.0.2 "cordova-custom-config"
    - cordova-plugin-app-preferences 0.99.3 "AppPreferences"
    - cordova-plugin-app-version 0.1.9 "AppVersion"
    - cordova-plugin-camera 2.4.1 "Camera"
    - cordova-plugin-compat 1.2.0 "Compat"
    - cordova-plugin-console 1.1.0 "Console"
    - cordova-plugin-device 1.1.7 "Device"
    - cordova-plugin-file 5.0.0 "File"
    - cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
    - cordova-plugin-splashscreen 4.0.3 "Splashscreen"
    - cordova-plugin-statusbar 2.2.3 "StatusBar"
    - cordova-plugin-whitelist 1.3.3 "Whitelist"
    - cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
    - es6-promise-plugin 4.1.0 "Promise"
    - ionic-plugin-keyboard 2.2.1 "Keyboard"
    - phonegap-plugin-barcodescanner 6.0.8 "BarcodeScanner"
- Dev machine OS and version, e.g.
    - OSX
        - ProductName:	Mac OS X
        - ProductVersion:	10.13
        - BuildVersion:	17A365
	
_iOS build issue:_
- Node JS version
    - 8.6.0

- Ionic environment info
    - cli packages: (/usr/local/lib/node_modules)
    - @ionic/cli-utils  : 1.16.0
    - ionic (Ionic CLI) : 3.16.0
- Installed Ionic Native modules and versions
    - ├── @ionic-native/app-preferences@4.3.3
    - ├── @ionic-native/app-version@4.3.3
    - ├── @ionic-native/barcode-scanner@4.3.3
    - ├── @ionic-native/camera@4.3.3
    - ├── @ionic-native/core@4.3.1
    - ├── @ionic-native/device@4.3.3
    - ├── @ionic-native/file@4.5.3
    - ├── @ionic-native/keyboard@4.3.3
    - ├── @ionic-native/photo-viewer@4.5.3
    - ├── @ionic-native/social-sharing@4.5.3
    - ├── @ionic-native/splash-screen@4.3.3
    - ├── @ionic-native/status-bar@4.3.3

**Related code:**

```
<custom-preference name="ios-XCBuildConfiguration-IPHONEOS_DEPLOYMENT_TARGET" value="10.0" />
```

**Other information:**
Thanks in advance!

**Comment by dpa99c** [comment]
This plugin relies on the Cordova plugin installation process, which since `cordova@7` uses `npm install` to install plugins to the project via `cordova-fetch` and in doing so to satisfy the [plugin dependencies](https://github.com/dpa99c/cordova-custom-config/blob/master/package.json#L31).

This missing dependency error [being raised](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/applyCustomConfig.js#L1158) because the script is failing to [load required dependent node modules](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/applyCustomConfig.js#L1097).

As you can see from the plugin's dependency list, `simple-plist` is not a direct dependency of the plugin, however from `npm list` I can see it's a dependency of the `xcode` module, which is a [direct dependency](https://github.com/dpa99c/cordova-custom-config/blob/master/package.json#L35).

Therefore, I would say that something in your build environment is causing `npm install` to not satisfy that dependency and that's not something that I can resolve by making code changes to this plugin, since it's simply relying on Cordova/NPM to satisfy its dependencies.

**Comment by alain-sarti** [comment]
Thank you for your input. I will have a look if there is something different on the build macbook.

I was sure that there seems to be a problem, since all the versions are identical on both systems and on the one it works on the other it doesn't.

**Comment by alain-sarti** [comment]
Okay, one last question. I asked a colleague to check out the repo, use npm install on his machine and it didn't work, too.

Are there any special steps to share a project with someone else if I want to use the plugin?

Thanks in advance :)

**Comment by alain-sarti** [comment]
Okay, the solution was for the macbook to remove the node_modules folder, to remove the platform and add the platform.

Very strange behaviour :/
But definately npm related

**Comment by dfa1234** [comment]
For me the solution was to enter `cd plugins/cordova-custom/config`
And to `npm i` there.
