### ISSUE TITLE
Github dependency

### ISSUE THREAD

**Issue by patrick-stirnemann** [dpa99c/cordova-custom-config#145]
**I'm submitting a ...**:
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**
"npm install" fails in our build pipeline because it cannot get the plist package due to the external reference to github.

**Expected behavior:**
Every reference in package.json should be done with a version number.

**Other information:**
package.json (version 5.0.2)
line 34: "plist": "xiangpingmeng/plist.js"

**Comment by dpa99c** [comment]
The reason that [a Github fork](https://github.com/xiangpingmeng/plist.js) of `plist.js` is referenced in the `package.json` is because the [versions published to NPM](https://www.npmjs.com/package/plist?activeTab=versions) contain an [unresolved bug](https://github.com/TooTallNate/plist.js/issues/79) which causes [issues in this plugin](https://github.com/dpa99c/cordova-custom-config/issues/136).

So until such time that a version of `plist` is published to npm which contains a fix, this plugin's `package.json` will continue to reference the Github repo which contains the bugfixed version.

**Comment by huerlisi** [comment]
According to https://github.com/TooTallNate/plist.js/pull/67#issuecomment-281022141 the referenced bug might well be fixed in the currently released version of `plist`.

Who could validate this?

We're expecting build failures with the current version of `cordova-custom-config` as we're behind a corporate proxy that prevents direct dependencies on github (we're using a local npm mirror).

Thanks for this package and all the awesome work here!

**Comment by devsheder** [comment]
Hi @dpa99c ,
I have the same problem as above : my client is behind a corporate proxy and we can't use the lastest versions of your plugin.
Were you able to contact xiangpingmeng ? Do we have to fork his project ?

Thx a lot for your work,
See you
