### ISSUE TITLE
i need help with error unboun prefix

### ISSUE THREAD

**Issue by monofdr** [dpa99c/cordova-custom-config#162]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\app\magnetodemo\camahueto\platforms\android\app\src\main\res\xml\config.xml:31: error: unbound prefix.

but the line 31 is this

    <icon gap:density="ldpi" gap:platform="android" src="icon.png" />

the xml file is this

[Nuevo documento de texto.txt](https://github.com/dpa99c/cordova-custom-config/files/3424216/Nuevo.documento.de.texto.txt)

**Comment by dpa99c** [comment]
The immediate error is caused because you are using an undeclared namespace - you need to declare it in your `<widget>` in `config.xml`:

    <widget xmlns     = "http://www.w3.org/ns/widgets"
        xmlns:gap = "http://phonegap.com/ns/1.0"

However the `gap` prefix is [specific to Phonegap Build](https://forums.adobe.com/thread/2418686) - this plugin will not work with Phonegap Build as it relies on Cordova hooks scripts (unsupported by Phonegap Build).
