### ISSUE TITLE
indexBy issue

### ISSUE THREAD

**Issue by oak-tree** [dpa99c/cordova-custom-config#17]
$ cordova prepare android
cordova-custom-config: Error updating config for platform 'android': _.indexBy is not a function
cordova-custom-config: Error updating config for platform 'ios': _.indexBy is not a function

$ cordova plugin remove cordova-custom-config
Uninstalling cordova-custom-config from android
Uninstalling cordova-custom-config from ios
Error: Expected "/* Begin ", "/* End ", "\"" or [A-Za-z0-9_.] but "<" found.

$ cordova plugin add cordova-custom-config
Fetching plugin "cordova-custom-config@~1.1.8" via npm
Installing "cordova-custom-config" for android
Installing "cordova-custom-config" for ios
Failed to install 'cordova-custom-config':undefined
Error: Expected "/* Begin ", "/* End ", "\"" or [A-Za-z0-9_.] but "<" found.

Any ideas?

**Comment by dpa99c** [comment]
I'm not able to reproduce these issues either on Windows 10/Android or OSX 10.11/iOS+Android. What platform are you encountering this on?

> cordova-custom-config: Error updating config for platform 'android': _.indexBy is not a function
> cordova-custom-config: Error updating config for platform 'ios': _.indexBy is not a function

Looks like the `lodash` module is not being loaded for some reason, hence [line 100](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/applyCustomConfig.js#L100) is raising this error. Check that `lodash` module is present: `npm list lodash`. If not, `npm install lodash`.

> Error: Expected "/* Begin ", "/* End ", "\"" or [A-Za-z0-9_.] but "<" found.

Appears to be a problem with the regular expression on [line 332](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/applyCustomConfig.js#L332) which is odd because it seems [perfectly valid](https://regex101.com/r/pG1lJ0/1).

**Comment by oak-tree** [comment]
Runnnig `npm install` at `<projectfolder>/plugins/cordova-custom-config` solved the issues above. But why do i have to run `npm install` manually?

**Comment by dpa99c** [comment]
On installing the plugin, it should automatically satisfy its dependencies via an [`after_install_plugin` hook in the config.xml](https://github.com/dpa99c/cordova-custom-config/blob/master/plugin.xml#L25) which invokes [a script](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/resolveDependencies.js) to resolve the npm dependencies.

My suggestion is to remove the plugin from the project, ensure that `plugins/cordova-custom-config` folder is entirely deleted and also remove the `{project}/node_modules` folder. Then run `cordova plugin add cordova-custom-config --verbose` to get some additional debug output when the plugin is being installed. It should report that dependencies are being resolved and installed, otherwise it will error.
