### ISSUE TITLE
indexBy renamed in lodash 4.0.0

### ISSUE THREAD

**Issue by danvirsen** [dpa99c/cordova-custom-config#20]
The package.json doesn't specify a version for lodash, so when lodash was updated to 4.0.0 yesterday this plugin broke since the function "indexBy" was renamed "keyBy".

**Comment by dpa99c** [comment]
Will fix this when I get a sec. Not as trivial as putting a version number in the package.json since I need to make the [dependency resolution script](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/resolveDependencies.js) respect the version number is the package.json - currently it does not.

**Comment by dpa99c** [comment]
Just published cordova-custom-config@1.1.9 to npm which should fix the immediate lodash issue by changing reference to "indexBy" to "keyBy". 

Turns out that specifying a package version when programmatically installing a module is trickier than I first thought. For some reason, specifying a version number in the form `npm install foo@x.y.z` causes the CLI command to return before it has finished downloading and installing the specified module, causing a race condition. Omitting it and using `npm install foo` does not cause this issue. I would like to fix the version numbers to prevent the next backwardly-incompatible dependency release breaking the plugin again, but need to overcome this race condition issue first.

**Comment by danvirsen** [comment]
That's a strange issue, but the speedy response quick fix is very much appreciated. :)
