### ISSUE TITLE
ios-XCBuildConfiguration preference tag's default Quote setting triggers ignore error during build

### ISSUE THREAD

**Issue by erichochhalter** [dpa99c/cordova-custom-config#27]
By default an `ios-XCBuildConfiguration` preference tag without a `quote` attribute renders the key and value into xcconfig file surrounded by double quotes. For example, the preference
```
<preference name="ios-XCBuildConfiguration-ENABLE_BITCODE" value="NO"/>
```
renders this line in xcconfig
```
"ENABLE_BITCODE" = "NO"
```

For me (using platform  cordova-ios 3.9.2), **when building with `cordova build ios --device`** this quoted entry throws an error (on `build-debug.xcconfig`):
```
Ignoring configuration file '/PATH_TO_CORDOVA_APP/platforms/ios/cordova/build-debug.xcconfig' because it could not be loaded.
  Reason: File could not be parsed due to an error: String '"ENABLE_BITCODE" = "NO"' could not be parsed: '"ENABLE_BITCODE"' is not a legal macro nameBuild settings from command line
```

Similarly, `cordova build ios --release --device` throws an error (on `build-release.xcconfig`):
```
Ignoring configuration file '/PATH_TO_CORDOVA_APP/platforms/ios/cordova/build-release.xcconfig' because it could not be loaded.
  Reason: File could not be parsed due to an error: String '"ENABLE_BITCODE" = "NO"' could not be parsed: '"ENABLE_BITCODE"' is not a legal macro nameBuild settings from command line
```

I was able to resolve my build issues by using the `quote` attribute in my preference in `config.xml`:
```
<preference name="ios-XCBuildConfiguration-ENABLE_BITCODE" value="NO" quote="none"/>
```

I believe quote="none" should be the default setting.

**Comment by dpa99c** [comment]
If I remember correctly, there was a reason I set the default to be quoted, but it's been a while since I looked at the code, so I'll have to take a look and get back to you.

I think it was because some keys and values that contain special values **had** to be quoted, otherwise the build would fail for similar reasons and I wasn't able to pin down a set of special characters in order to auto-detect them and just do the right thing. If memory serves, issue #13 is an example of this, and I also remember encountering problems with code signing identities, where keys and values had to be quoted, for example:

    <preference name="ios-XCBuildConfiguration-CODE_SIGN_IDENTITY[sdk=iphoneos9.1]" value="Custom Distribution (iOS 9.1)" buildType="release" />

**Comment by dpa99c** [comment]
Commit 584640651a4b615f1b9b979e51a3282cfb80e537 should also resolve this. Please try v1.2.0 (now default on npm) and let me know if you have any issues.

**Comment by dpa99c** [comment]
Should be fixed - reopen if not
