### ISSUE TITLE
Merging existing configs / tags / attributes

### ISSUE THREAD

**Issue by leoc** [dpa99c/cordova-custom-config#30]
I am currently trying to just set one additional attribute for the `<appliction>` config.

That attribute is `android:name="MainApp"`. However:

```
    <config-file target="AndroidManifest.xml">
        <application android:name="MainApplication" />
    </config-file>
```

causes the build to replace the whole `application` tag.

Is there a possibility to let the build process merge this attribute into the existing config?

**Comment by dpa99c** [comment]
A config block is intended to insert a new block of config, not modify an existing one. Use a preference to add an attribute to an existing element:

    <preference name="android-manifest/application/@android:name" value="MainApplication" />

**Comment by dpa99c** [comment]
Documentation has been updated to make this clearer. However, merging the XML subtree defined in the config-file element with the existing tree in AndroidManifest.xml is non-trivial and currently I can't see a use case for it (since preferences can be used to modify attributes on existing elements), therefore I'm going to close this.
