### ISSUE TITLE
appears to be deleting project level package.json file

### ISSUE THREAD

**Issue by johnkcox** [dpa99c/cordova-custom-config#31]
version 1.2.2

after running `$cordova prepare ios --verbose` you see these lines in the output near the end:

```
cordova-custom-config: Completed npm install
cordova-custom-config: Installed modules
cordova-custom-config: Removed our package.json
cordova-custom-config: Dependency resolution complete
```
Shortly thereafter you'll notice that your `package.json` file at the project level is missing. That's no good. I didn't see this happen before today.

**Comment by dpa99c** [comment]
This is a lesson why not to `npm publish` after a few beers :-)

v1.2.2 attempts to address race conditions in dependency resolution present in previous versions by using a single `npm install` command in the project root. However, in order to do this, the plugin's own package.json must be located there.

Since cordova itself doesn’t provide any mechanism for plugins to install npm dependencies, this is all wild wild west. 

In the case that a "real" project-level package.json already exists, the plugin should [check if it exists](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/resolveDependencies.js#L78) and if so [copy it to a temp file](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/resolveDependencies.js#L81) (package.json.tmp) before [restoring it to package.json](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/resolveDependencies.js#L120) after dependencies have been installed. 

However, I can see now what's happening in your case is that the resolution script is being run twice - once on before_prepare and once on after_prepare, so the two concurrent script instances are overlapping, with the result of removing your project-level package.json. I'll try to fix that now and push out a fix as (easy as) 1.2.3

**Comment by dpa99c** [comment]
I've just published v1.2.3 to npm - this should fix the problem of removal of project-level package.json.
Let me know if this resolves your issue or not.

**Comment by johnkcox** [comment]
Hey - thanks for the quick turnaround! I picked up 1.2.3 and it appears that my package.json file is intact!

**Comment by dpa99c** [comment]
Cool, 1.2.3 fixed it :-)
