### ISSUE TITLE
Removing manifest elements

### ISSUE THREAD

**Issue by xtianus** [dpa99c/cordova-custom-config#39]
This looks like a good replacement for the [phonegap-build equivalent](http://docs.build.phonegap.com/en_US/configuring_config_file_element.md.html) but a quick read of your documentation shows no support for removing configuration elements. For example, to remove a bunch of permissions I would do in phonegap-build:

```xml
    <gap:config-file platform="android" parent="/manifest" mode="delete">
      <uses-permission android:name="android.permission.CAMERA"/>
      <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
      <uses-feature android:name="android.hardware.camera" android:required="false"/>
    </gap:config-file>
```

Could this be added?

Thank you.

**Comment by dpa99c** [comment]
Short answer: no (well, probably not)

Long answer: Explicit removal of custom config from the platform configs is something I've considered, but it's more complicated that it might at first seem. Whereas Phonegap Build is a build environment entirely under the control of Adobe, this plugin is simply just that, another plugin that gets no special treatment and can be used in any number of build environments. 

Using your example above, if this plugin supported a similar attribute to `android:required="false"`, then you'd expect `<uses-feature android:name="android.hardware.camera"/>` not to appear in the AndroidManifest.xml right? But since this plugin is reliant on Cordova/Phonegap's hooks to carry out its operations (e.g. the `after_prepare` hook), what if another plugin adds the same element in its own hook? There's no guarantee that this plugin hook will be executed after the other plugin hook, so no guarantee of the outcome. For Phonegap Build, because they control the entire build environment, they can post-process the resulting output of all the plugins before moving on to the build phase.

For config-file blocks, it gets even more complex as the plugin would need to identify a subtree of the platform config that relates to the config-file block in the original config.xml in order to remove it. And again, what if something else had modified that subtree after it was added? It all gets rather messy.

Hence, the best solution I was able to come up with was the [auto-backup/restore feature](https://github.com/dpa99c/cordova-custom-config#backups), where the plugin will take a backup copy of platform config files (i.e. AndroidManifest.xml) before it makes any modifications, then restore these backups to overwrite the existing files before re-applying dynamic config based on the current custom config in config.xml. The idea being that if you remove a custom config entry from config.xml, this effectively "removes" it from the platform config file because it just doesn't apply it to the original backup copy.

If you've got any suggestions about how removal of entries could be done in a smarter way, I'd be grateful to hear them, but as it stands it's not something I'm planning to support.

**Comment by pke** [comment]
Ah I just tried to remove not needed plist entries with just providing an empty config-block. But it didn't work. Wanted to fix the issue mentioned over here [in your diagnostic plugin](https://github.com/dpa99c/cordova-diagnostic-plugin/issues/181#issuecomment-281963144)
