### ISSUE TITLE
Add localized entries to ios plist

### ISSUE THREAD

**Issue by pke** [dpa99c/cordova-custom-config#57]
Is there a way to add localized keys/strings to ios `plist` files with this plugin? Especially for the `NSLocationWhenInUseUsageDescription`

**Comment by dpa99c** [comment]
The [Apple documentation](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html#//apple_ref/doc/uid/TP40009254-102276) indicates that to add localized strings to an app on iOS requires creating new language-specific folders and plist files, as well as inserting keys into the master plist file.

While this plugin can currently be used to do the latter, it does not support the creation or modification of the folders and other plist files, so this would need to be done manually via XCode or otherwise.

**Comment by pke** [comment]
Yeah seems really complicated. I wonder if there is another plugin to handle this.
