### ISSUE TITLE
write config settings to xcconfig files

### ISSUE THREAD

**Issue by contra** [dpa99c/cordova-custom-config#6]
right now this doesnt write to xcconfig files, so on archive actions the settings dont have any effect

**Comment by dpa99c** [comment]
Going by the [unofficial guide](http://pewpewthespells.com/blog/xcconfig_guide.html):

> A xcconfig file is used as a supplemental file to a specific build configuration. 
> A build configuration can have an associated xcconfig file, this allows for additional changes to the target's build settings from outside the Xcode project editor

The changes the plugin currently makes to the *-Info.plist and project.pbxproj files emulate changes that you could otherwise make directly through the user interface of XCode. These changes will be reflected in builds and archive actions, in the same way that changes made through the XCode UI would. However, xcconfig files enable additional changes to be made for specific build configurations external to the XCode editor. While this is another way that the plugin could apply settings to the iOS platform, it seems simpler to me to directly change the XCode project and plist files, so the changes can be seen to be reflected in the UI when the project is opened in Xcode.

**Comment by contra** [comment]
@dpa99c Sure, writing to only plist files would be great if that actually worked - Like I said in the original issue, when building and archiving it seems like xcode also checks xcconfig files which means anything you changed in your plist file means nothing during those actions.

**Comment by dpa99c** [comment]
Just to be clear, this plugin works fine when writing to plist/pbxproj files if the project **doesn't contain  xcconfig files**. You can satisfy yourself of this by building and running the [example project](https://github.com/dpa99c/cordova-custom-config-example).

A vanilla Cordova project does not use xcconfig files and at the point where you add them to your project you are choosing to override the settings defined in plist/pbxproj. I'm fairly certain this means that any changes Cordova itself then then makes to the plist/pbxproj files will also be overriden by the xcconfig files and have no effect. Therefore I deem it beyond the scope of what this plugin is intended for.

I'd suggest that if you want this functionality, you fork the plugin and implement a mechanism by which xcconfig files can be detected and modified in favour of plist/pbxproj changes.

**Comment by contra** [comment]
@dpa99c A vanilla cordova project created with the latest version of cordova-ios *does* use xcconfig files (you can see them [here](https://github.com/apache/cordova-ios/tree/master/bin/templates/scripts/cordova)). I would assume a plugin called **cordova-custom-config** would be capable of **customizing the cordova config**, but if you believe this is out of scope go ahead and close the issue.

If this is the case, it might be a good idea to change the name of the plugin to help avoid confusion: perhaps `cordova-customize-some-of-your-config` or `cordova-partial-config-customization` would be more apt for what it actually does.
