### ISSUE TITLE
Cannot override minSdkVersion on android manifest

### ISSUE THREAD

**Issue by gustavocampos** [dpa99c/cordova-custom-config#60]
I've moved from Phonegap Build 5.2.0 to 6.1.0, then it started to ignore my preferences and generate minSdkVersion 15+, my preferences were:
```
<preference name="android-minSdkVersion" value="21" />
<preference name="android-targetSdkVersion" value="23" />
```
I tried to use this plugin to overwrite sdk version on manifest but it's not working, I've tried both:
```
<preference name="android-manifest/uses-sdk/@android:minSdkVersion" value="21" />
<preference name="android-manifest/uses-sdk/@android:targetSdkVersion" value="23" />
```
and
```
<config-file target="AndroidManifest.xml" parent="/*">
    <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="23" />
</config-file>
```
without success.

Any thoughts on this?

**Comment by dpa99c** [comment]
This plugin will not work with Phonegap Build as it now [does not support the use of hooks scripts](https://github.com/phonegap/build/issues/425) which this plugin relies on - I will update the plugin documentation to clarify this.

The reason that `android-minSdkVersion` and `android-targetSdkVersion` worked before on Phonegap Build is that these preferences are (or at least were) supported natively by Cordova/Phonegap. If they have stopped working in the Phonegap Build environment, it is either because Phonegap or Phonegap Build has dropped direct support for them, but regardless, this plugin cannot help you in the Phonegap Build environment.

**Comment by dpa99c** [comment]
Updated docs to clarify this: https://github.com/dpa99c/cordova-custom-config#important-note-for-phonegap-build--intel-xdk

**Comment by gustavocampos** [comment]
Thanks for answering me, also, I would like to note that phonegap-barcodescanner-plugin is forcing min sdk version to 15+ so it's a plugin problem, not a cordova/phonegap problem.

**Comment by dpa99c** [comment]
ok, thanks for clarifying
