### ISSUE TITLE
Error when adding platform or prepare on ios: Cannot find lodash module

### ISSUE THREAD

**Issue by veronicabend** [dpa99c/cordova-custom-config#78]
I have been using this plugin ok, previous versions.

Today I created a project and the version that got installed was 3.0.11

I kept having a depedancy error when adding ios platform, or when running cordova prepare ios, that the plugin cannot find lodash module.

I updated npm, I am running 3.10.9 . I installed lodash in case it was missing

npm install -g lodash

It got installed

Nothing solved the error. When I uninstalled the plugin and forced version 2.0.3 to be installed, then it worked ok.

How can I use the newer version?

Thanks

**Comment by dpa99c** [comment]
It appears that there's sometimes issues with an existing project that was created under npm@2, after updating to npm@3 (see #77). I would assume this is due to the different structure of `node_modules` between the two versions. Try removing the existing `node_modules` in the project then re-installing:

    rm -Rf node_modules && npm install

**Comment by dpa99c** [comment]
Reopen if still an issue
