### ISSUE TITLE
Refusing to install cordova-custom-config as a dependency of itself

### ISSUE THREAD

**Issue by deliverymanager** [dpa99c/cordova-custom-config#87]
Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Node Version: v5.12.0
NPM Version: 3.10.9
cordova android version: 6.0.0

I am trying to install the plugin but it fails with the message below:

cordova-custom-config: npm dependencies missing - installing
Failed to install 'cordova-custom-config':undefined
Error: Error installing npm dependencies: Error: Command failed: npm install cordova-custom-config
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "cordova-custom-config"
npm ERR! node v5.12.0
npm ERR! npm  v3.10.9
npm ERR! code ENOSELF

npm ERR! Refusing to install cordova-custom-config as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/anestis/Dropbox/Applications/supercourse/bookbuilder/npm-debug.log

**Comment by dpa99c** [comment]
Should be fixed in `cordova-custom-config@3.1.0`. 
If still an issue, let me know, and I'll reopen.

**Comment by wwilbor** [comment]
Hi, I have the same problem. There are any update? I understand that will be fixed in 3.1.0 but I noticed is not. See my log:
PS: I tried to downgrade to old version but I don't know why my project claims everytime about cordova-custom-config plugin and is not compile to android. Any idear what is?

 
LOG: 

Wilsons-MacBook-Pro:ChecklistMobile wwilbor$ sudo npm install cordova-custom-config
Password:
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "cordova-custom-config"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install cordova-custom-config as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wwilbor/Desktop/GDrive-Sysmobil/wwistuba/Projetos-Mac/Checklist/ChecklistMobile/npm-debug.log



Thanks a lot
